import { useState } from "react";
import Link from "next/link";
import { Activity, ArrowRight, CalendarDays, Check, ClipboardList, Clock3, Copy, FilePlus2, LibraryBig, MessageCircle, MoreHorizontal, Plus, Search, Send, Users } from "lucide-react";
import { Badge, Button, Card, displayDate, Empty, Field, Input, LinkAction, Modal, PageTitle, SectionTitle, Select } from "./ui";

const nameFor = (data, id) => data.patients.find(person => person.id === id)?.name || "Patient";
const exerciseFor = (data, id) => data.exercises.find(exercise => exercise.id === id)?.name || "Exercise";

export function Dashboard({ data, user, open, onCreate }) {
  const review = data.sessions.filter(session => !session.reviewed);
  const cards = [[Users, data.patients.length, "Patients", "blue"], [LibraryBig, data.exercises.length, "Exercises", "violet"], [CalendarDays, data.sessions.length, "Sessions", "mint"], [ClipboardList, review.length, "To review", "amber"]];
  return <><PageTitle eyebrow="THERAPIST DASHBOARD" title={`Good morning, ${user.name.split(" ")[0]}`} text="Here is what needs your attention today." action={<Button onClick={onCreate}><Plus size={17}/> Create exercise</Button>}/>
    <div className="metrics">{cards.map(([Icon, value, label, tone]) => <Card className="metric-card" key={label}><span className={`metric-icon ${tone}`}><Icon size={22}/></span><strong>{value}</strong><span>{label}</span></Card>)}</div>
    <div className="dashboard-columns"><Card className="content-card"><SectionTitle title="Sessions to review" text="Recent patient activity" action={<LinkAction onClick={() => open("Sessions")}>View sessions</LinkAction>}/>{review.length ? review.slice(0,5).map(session => <div className="activity-row" key={session.id}><span className="mini-avatar">{nameFor(data, session.patientId).slice(0,2).toUpperCase()}</span><div><strong>{nameFor(data, session.patientId)}</strong><small>{exerciseFor(data, session.exerciseId)}</small></div><Badge tone="amber">Review</Badge></div>) : <Empty icon={ClipboardList} title="All caught up" text="Completed practice sessions will appear here."/>}</Card>
    <Card className="content-card"><SectionTitle title="Recent messages" text="Stay in touch with patients" action={<LinkAction onClick={() => open("Messages")}>Open messages</LinkAction>}/>{data.messages.length ? data.messages.slice(-4).reverse().map(message => <div className="activity-row" key={message.id}><span className="mini-avatar soft">{nameFor(data, message.patientId).slice(0,2).toUpperCase()}</span><div><strong>{nameFor(data, message.patientId)}</strong><small>{message.text}</small></div><span className="quiet">{message.at}</span></div>) : <Empty icon={MessageCircle} title="No messages yet" text="Conversations with patients will show here."/>}</Card></div>
    <div className="space-top"><SectionTitle title="Exercise library" text="Your movement plans" action={<LinkAction onClick={() => open("Exercises")}>Browse library</LinkAction>}/></div><div className="exercise-tile-grid">{data.exercises.slice(0,3).map(exercise => <button key={exercise.id} className="exercise-tile" onClick={() => open("Exercises")}><span className="exercise-tile-art"><Activity size={36}/></span><span className="exercise-tile-content"><Badge tone={exercise.status === "Published" ? "mint" : "amber"}>{exercise.status}</Badge><strong>{exercise.name}</strong><small>{exercise.region} · {exercise.reps} reps</small><span>Open exercise <ArrowRight size={16}/></span></span></button>)}</div>{!data.exercises.length && <Card><Empty icon={LibraryBig} title="Your library is empty" text="Create your first exercise to get started." action={<Button onClick={onCreate}><Plus size={16}/> Create exercise</Button>}/></Card>}</>;
}

export function ExerciseLibrary({ data, mutate, onCreate, onEdit }) {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("All"); const [menu, setMenu] = useState(null); const [assigning, setAssigning] = useState(null); const [patientId, setPatientId] = useState(""); const [error, setError] = useState("");
  const filtered = data.exercises.filter(exercise => exercise.name.toLowerCase().includes(query.toLowerCase()) && (status === "All" || exercise.status === status));
  const edit = exercise => { setMenu(null); onEdit(exercise.status === "Draft" ? structuredClone(exercise) : { ...structuredClone(exercise), id: undefined, supersedesId: exercise.id, version: exercise.version + 1, status: "Draft" }); };
  const duplicate = async exercise => { try { await mutate("/exercises", { method: "POST", body: { ...exercise, id: undefined, supersedesId: null, version: 1, name: `${exercise.name} copy`, status: "Draft" } }, "Draft duplicated"); setMenu(null); } catch (problem) { setError(problem.message); } };
  const archive = async exercise => { try { await mutate(`/exercises/${exercise.id}/archive`, { method: "POST" }, "Exercise archived"); setMenu(null); } catch (problem) { setError(problem.message); } };
  const assign = async () => { try { await mutate("/assignments", { method: "POST", body: { exerciseId: assigning.id, patientId } }, "Exercise assigned"); setAssigning(null); setError(""); } catch (problem) { setError(problem.message); } };
  return <><PageTitle eyebrow="EXERCISE LIBRARY" title="Exercises" text="Build, publish and assign movement plans." action={<Button onClick={onCreate}><Plus size={17}/> Create exercise</Button>}/><Card className="table-surface"><div className="table-toolbar"><div className="search-field"><Search size={18}/><Input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search exercises"/></div><Select value={status} onChange={event => setStatus(event.target.value)}><option>All</option><option>Published</option><option>Draft</option><option>Archived</option></Select></div><div className="table-scroll"><table className="data-table"><thead><tr><th>EXERCISE</th><th>REGION</th><th>VERSION</th><th>STATUS</th><th/></tr></thead><tbody>{filtered.map(exercise => <tr key={exercise.id}><td><div className="table-identity"><span className="table-symbol"><Activity size={20}/></span><span><strong>{exercise.name}</strong><small>{exercise.reps} reps · {exercise.hold}s hold</small></span></div></td><td>{exercise.region}</td><td>v{exercise.version}</td><td><Badge tone={exercise.status === "Published" ? "mint" : exercise.status === "Draft" ? "amber" : "gray"}>{exercise.status}</Badge></td><td className="action-cell"><button className="small-icon-button" onClick={() => setMenu(menu === exercise.id ? null : exercise.id)} aria-label={`Actions for ${exercise.name}`}><MoreHorizontal size={19}/></button>{menu === exercise.id && <div className="action-menu"><button onClick={() => edit(exercise)}><FilePlus2 size={16}/> {exercise.status === "Draft" ? "Edit draft" : "Create new version"}</button><button onClick={() => duplicate(exercise)}><Copy size={16}/> Duplicate as draft</button>{exercise.status === "Published" && <button onClick={() => { setAssigning(exercise); setPatientId(data.patients[0]?.id || ""); setMenu(null); }}><Users size={16}/> Assign patient</button>}{exercise.status !== "Archived" && <button onClick={() => archive(exercise)}>Archive</button>}</div>}</td></tr>)}</tbody></table>{!filtered.length && <Empty icon={LibraryBig} title="No exercises found" text={data.exercises.length ? "Try a different search or status." : "Create an exercise to start your library."} action={!data.exercises.length && <Button onClick={onCreate}><Plus size={16}/> Create exercise</Button>}/>}</div></Card>{error && <p className="form-error">{error}</p>}{assigning && <Modal title="Assign exercise" text={`Assign ${assigning.name} to a patient.`} onClose={() => { setAssigning(null); setError(""); }}><Field label="Patient"><Select value={patientId} onChange={event => setPatientId(event.target.value)}>{data.patients.map(person => <option key={person.id} value={person.id}>{person.name}</option>)}</Select></Field>{!data.patients.length && <p>Create a patient first.</p>}{error && <p className="form-error">{error}</p>}<Button disabled={!patientId} onClick={assign}>Assign exercise <ArrowRight size={16}/></Button></Modal>}</>;
}

export function Patients({ data, mutate, onMessage }) {
  const [adding, setAdding] = useState(false); const [form, setForm] = useState({ name: "", email: "", focus: "" }); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const add = async event => { event.preventDefault(); setBusy(true); setError(""); try { await mutate("/patients", { method: "POST", body: { ...form, email: form.email.trim() || null } }, "Patient created"); setAdding(false); setForm({ name: "", email: "", focus: "" }); } catch (problem) { setError(problem.message); } finally { setBusy(false); } };
  return <><PageTitle eyebrow="PEOPLE IN YOUR CARE" title="Patients" text="Create patient access and manage care plans." action={<Button onClick={() => setAdding(true)}><Plus size={17}/> Add patient</Button>}/><div className="patient-card-grid">{data.patients.map(person => <Card className="patient-card" key={person.id}><div className="patient-card-top"><span className="person-avatar">{person.initials}</span><Badge tone="mint">Active</Badge></div><h2>{person.name}</h2><p>{person.focus || person.email || "Patient"}</p><div className="patient-stat"><span><LibraryBig size={16}/> {data.assignments.filter(item => item.patientId === person.id).length} assigned</span><span><Clock3 size={16}/> {data.sessions.filter(item => item.patientId === person.id).length} sessions</span></div><div className="patient-card-actions"><Button tone="secondary" onClick={() => onMessage(person.id)}><MessageCircle size={16}/> Message</Button><Link href={`/patient?patientId=${person.id}`} className="button button-ghost">Patient view <ArrowRight size={16}/></Link></div></Card>)}</div>{!data.patients.length && <Card><Empty icon={Users} title="No patients yet" text="Add your first patient to begin assigning exercises." action={<Button onClick={() => setAdding(true)}><Plus size={16}/> Add patient</Button>}/></Card>}{adding && <Modal title="Add patient" text="Add a patient to this workspace. They can open their view directly." onClose={() => setAdding(false)}><form className="modal-form" onSubmit={add}><Field label="Full name"><Input required minLength={2} value={form.name} onChange={event => setForm({ ...form, name: event.target.value })}/></Field><Field label="Email (optional)"><Input type="email" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })}/></Field><Field label="Care focus"><Input value={form.focus} onChange={event => setForm({ ...form, focus: event.target.value })} placeholder="Optional"/></Field>{error && <p className="form-error">{error}</p>}<Button disabled={busy} type="submit">{busy ? "Creating…" : "Create patient"}</Button></form></Modal>}</>;
}

export function Sessions({ data, mutate }) { const [selected, setSelected] = useState(null); const [error, setError] = useState(""); const review = async () => { try { await mutate(`/sessions/${selected.id}/review`, { method: "PATCH" }, "Session reviewed"); setSelected(null); } catch (problem) { setError(problem.message); } }; return <><PageTitle eyebrow="PATIENT ACTIVITY" title="Sessions" text="Review practice completed by your patients."/><Card className="table-surface"><div className="table-scroll"><table className="data-table"><thead><tr><th>PATIENT</th><th>EXERCISE</th><th>DATE</th><th>STATUS</th><th/></tr></thead><tbody>{data.sessions.map(session => <tr key={session.id}><td><strong>{nameFor(data, session.patientId)}</strong></td><td>{exerciseFor(data, session.exerciseId)}</td><td>{displayDate(session.completedAt)}</td><td><Badge tone={session.reviewed ? "mint" : "amber"}>{session.reviewed ? "Reviewed" : "Review"}</Badge></td><td><button className="link-action" onClick={() => setSelected(session)}>Open <ArrowRight size={15}/></button></td></tr>)}</tbody></table>{!data.sessions.length && <Empty icon={ClipboardList} title="No sessions yet" text="Patient practice sessions will appear here."/>}</div></Card>{selected && <Modal title="Session review" text={`${nameFor(data, selected.patientId)} · ${exerciseFor(data, selected.exerciseId)}`} onClose={() => setSelected(null)}><div className="summary-lines"><div><span>Completed</span><strong>{displayDate(selected.completedAt)}</strong></div><div><span>Repetitions</span><strong>{selected.reps ?? 0} / {selected.targetReps ?? 0}</strong></div><div><span>Tracking coverage</span><strong>{Math.round((selected.trackingCoverage || 0) * 100)}%</strong></div></div><p className="quiet-note">Repetitions are camera estimates. Review the result with the patient when needed.</p>{error && <p className="form-error">{error}</p>}<Button disabled={selected.reviewed} onClick={review}><Check size={16}/> {selected.reviewed ? "Reviewed" : "Mark reviewed"}</Button></Modal>}</>; }

export function Messages({ data, user, portal, selectedPatient, setSelectedPatient, mutate }) { const [text, setText] = useState(""); const [error, setError] = useState(""); const patientId = portal === "patient" ? user.id : selectedPatient || data.patients[0]?.id; const person = data.patients.find(item => item.id === patientId); const messages = data.messages.filter(item => item.patientId === patientId); const send = async event => { event.preventDefault(); if (!text.trim()) return; try { await mutate("/messages", { method: "POST", body: { patientId, text: text.trim() } }); setText(""); setError(""); } catch (problem) { setError(problem.message); } }; return <><PageTitle eyebrow="CONVERSATIONS" title="Messages" text="Keep care conversations in one place."/><Card className="chat-layout"><div className="conversation-list">{portal === "therapist" ? data.patients.map(item => <button key={item.id} className={patientId === item.id ? "selected" : ""} onClick={() => setSelectedPatient(item.id)}><span className="mini-avatar">{item.initials}</span><span><strong>{item.name}</strong><small>{item.focus || item.email || "Patient"}</small></span></button>) : <div className="conversation-person"><span className="mini-avatar">{data.therapist?.initials}</span><span><strong>{data.therapist?.name}</strong><small>Your therapist</small></span></div>}</div><div className="conversation-main"><div className="conversation-header"><span className="mini-avatar">{portal === "therapist" ? person?.initials : data.therapist?.initials}</span><div><strong>{portal === "therapist" ? person?.name || "Select a patient" : data.therapist?.name}</strong><small>{portal === "therapist" ? "Patient" : "Therapist"}</small></div></div><div className="message-list">{messages.length ? messages.map(item => <div className={`message-bubble ${item.from === portal ? "mine" : ""}`} key={item.id}><p>{item.text}</p><small>{item.at}</small></div>) : <div className="conversation-empty">No messages yet. Start the conversation here.</div>}</div><form className="message-form" onSubmit={send}><Input value={text} onChange={event => setText(event.target.value)} disabled={!patientId} placeholder="Write a message…"/><button disabled={!patientId || !text.trim()} type="submit" aria-label="Send message"><Send size={18}/></button></form>{error && <p className="form-error">{error}</p>}</div></Card></>; }
